### ISSUE TITLE
菜谱管理中的所有内容，貌似都删除不了

### ISSUE THREAD

**Issue by Gray-wen** [Gray-wen/CYDC#2]

**Comment by sdcb** [comment]
只要某菜谱被点过一次餐，就无法删除；
如果有不同的菜谱，应该尽量创建一个新的菜谱，然后将旧菜谱改成不可用。

刷新页面后，我们需要将可用的菜谱显示在页面最前面；
删除已经被引用的菜谱，我们需要作出更友好的提示，告诉管理员“该菜谱已经被引用过，不能删除”

**Comment by JoleneZhao** [comment]
好的，了解~
另外，口味管理、地点管理的内容，也不能删除，这些应该是能够删除的？

**Comment by sdcb** [comment]
口味管理、地点管理的也一样，只要被任意一个FoodOrder引用就不能删除。
我们需要同菜谱一样，提供“是否可用”的功能，需要新建一个issue。
