### ISSUE TITLE
用户管理按金额排序

### ISSUE THREAD

**Issue by JoleneZhao** [Gray-wen/CYDC#24]
希望金额为正数的放顶前面，因为这是预付了、提前订餐的，可以一眼就看到，不会漏掉。
然后是欠款的，最后是不欠款的。

**Comment by sdcb** [comment]
可否加上一个下拉框作为查询条件：
1、预付了、提前订餐
2、不欠款
3、欠款

我们仍然保持现有排序。

**Comment by JoleneZhao** [comment]
可以
