### ISSUE TITLE
点餐时间，有些人的乱了

### ISSUE THREAD

**Issue by JoleneZhao** [Gray-wen/CYDC#25]
点餐的时间，有些人的是乱的，如图：
![image](https://cloud.githubusercontent.com/assets/16996747/12741264/c4548e88-c9b5-11e5-948f-876ba90ded1b.png)

**Comment by sdcb** [comment]
**可能**是因为点餐时错信了客户端时间造成的。

**Comment by sdcb** [comment]
1、解释：我们使用浏览器本地时间；
2、需要解决一下时间显示负数的问题。
