### ISSUE TITLE
晚上点餐时间24小时制问题

### ISSUE THREAD

**Issue by itbeartxx** [Gray-wen/CYDC#28]
![qq 20160203091628](https://cloud.githubusercontent.com/assets/3634572/12769885/7f3d1b48-ca56-11e5-914b-8edc761e05ac.png)

**Comment by itbeartxx** [comment]
如下午3点点的晚餐应显示15:00或03:00pm目前显示03:00

**Comment by sdcb** [comment]
after the merge, gray-wen resolved it.
