### ISSUE TITLE
账单明细

### ISSUE THREAD

**Issue by JoleneZhao** [Gray-wen/CYDC#34]
现在只有在用户管理那里有添加金额的功能，然后自动扣付，具体哪顿付了、哪顿没有付，并查不到。
希望在添加金额自动扣付的基础上，加上一个明细，让我可以将客户付的金额精确到没一顿，这样才知道客户到底是哪顿付了、哪顿没有付。
可以在点餐列表那儿加一栏“付款”，如果已付了就显示已付状态， 如果未付能让我点击付款。

**Comment by sdcb** [comment]
现在显示付款了。
