### ISSUE TITLE
地点、口味的排序

### ISSUE THREAD

**Issue by JoleneZhao** [Gray-wen/CYDC#9]
如果不能记忆上次的选择，那么是否可以让管理员设置地点、口味的默认值？现在默认的是易观，口味是清淡，希望能默认辰运，口味默认是辣

**Comment by sdcb** [comment]
目前地点和口味是按数据库中的顺序来的，我们稍后可以考虑添加一个优先级，显示的列表默认按优先级来排序。

我已经将数据更新排列了一下，现在数据库中的顺序为：
辰运
蜜獾
易观国际

**Comment by sdcb** [comment]
我觉得有正确的顺序后，不需要再作顺序了，close。
